application:
  security:
    jwt:
      secret-key: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
      expiration: 86400000000
      refresh-token:
        expiration: 60480000000
spring:
  datasource:
    url: ${NOTION_SECURITY_DATABASE_URL:jdbc:postgresql://localhost:5432/notion_security}
    username: ${NOTION_SECURITY_DATABASE_USERNAME:postgres}
    password: ${NOTION_SECURITY_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localh–ªost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"

